MACBOOK_MONITOR = 'Color LCD'

DESK_LEFT_MONITOR = 'DELL P2417H'
DESK_RIGHT_MONITOR = 'DELL P2417H'

-- LAB_LEFT_MONITOR = 'HP ZR2740w'
-- LAB_RIGHT_MONITOR = 'DELL P2715Q'

-- HOME_MONITOR_MAIN = 'DELL ST2420L'
-- HOME_MONITOR_SECONDARY = 'Acer X193W+'

IDEs = {
  'VSCode',
  'vim',
}
