# Configuration for direnv
# https://direnv.net/man/direnv.toml.1.html

[global]
# Redirect stdin to /dev/null during the .envrc evaluation
disable_stdin = false

# Also look for and load .env files on top of the .envrc files.
# If both .envrc and .env files exist, the .envrc will always be chosen first.
load_dotenv = false

# Load the .envrc with `set -euo pipefail`
strict_env = true

# Hides the diff of the environment variables when loading the .envrc
hide_env_diff = false

[whitelist]
prefix = [ "~/Code/Aledade" ]
